# Site settings
title: Bleuprint
email: johnotander@gmail.com
description: "A minimal Jekyll template with build tasks for scaffolding out responsive websites."
baseurl: "/bleuprint"
url: "http://4711.github.io"

author:
  name: "John Otander"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['bower_components', 'node_modules', 'scss', 'package.json', 'README.md', 'gulpfile.js', 'bower.json']
